### ISSUE TITLE
Somehow some words are changed in /stats words

### ISSUE THREAD

**Issue by hndrk-themer** [mkdryden/telegram-stats-bot#5]
Hey im using the latest version of your awesome bot on Python 3.8.4 on a raspberry pi 3b+ with an extern postgres12. So far the bot is working well since yesterday and stats are collected. what ive noticed that the output of /stats words has some weird results. Ill give two examples:

Text written in Chat: beautiful
Stats output: beauti

or
Text written in Chat: widgy
Stats output: widgi

**Comment by mkdryden** [comment]
Yes, this is normal. Words are normalized into lexemes because it is using the tsvector column in the database for this that is used to make the lquery option work. There is a way to make it not normalize and count individual words instead but it makes searching less powerful. When I get around to making an options system, I will add the ability to control this behaviour. See https://www.postgresql.org/docs/current/textsearch-intro.html for more details about this.

**Comment by hndrk-themer** [comment]
Oh sorry to open up this issue then and thanks for clarifying ;)) you did a great job and im happy i enhance my group with ur bot .
